# Workflow name
name: Lint and Test Code
on:
  # Triggers when code is pushed to the main branch
  push:
    branches: [main]
  # Triggers when a pull request is created against the main branch
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repository code to the runner
      - uses: actions/checkout@v4
      
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Specify the Python version to use
      
      # Install required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Ensure pip is up to date
          pip install ruff pytest  # Install linting and testing tools
      
      # Run the Ruff linter to check code quality
      - name: Run Ruff
        run: |
          ruff check .  # Lint all code in the repository
      